### ISSUE TITLE
Single segment namespace

### ISSUE THREAD

**Issue by weavejester** [yeller/yeller_clojure#1]
I notice that yeller-clojure-client uses a single segment namespace. This compiles as a packageless Java class, which can cause subtle issues around AOT compilation and integration with Java, and is why most libraries use `foo.core` instead of just `foo`. Perhaps `yeller.clojure.client` should be used instead?

**Comment by tom-pang** [comment]
@weavejester thanks! Fixed and bumped the version to `1.0.0` - This client is fully production ready. Now just to update all Yeller's open source libraries as well.
