### ISSUE TITLE
Documentation is wrong for new version

### ISSUE THREAD

**Issue by mrmemes-eth** [yeller/yeller_clojure#2]
The 1.0 release did not bring with it an accompanying documentation update. As it stands the code examples are mostly broken due to requiring namespaces that are no longer available.

**Comment by tom-pang** [comment]
@voxdolo thanks for the heads up.

Was this just the README? If so, fixed. If I missed any other docs, can you point me at them?

**Comment by mrmemes-eth** [comment]
@tcrayford it was. Thanks for the quick fix. Closing.
